name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: build && tests for ${{ matrix.name }}
    runs-on: ubuntu-22.04
    env:
      CGO_ENABLED: '0'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux amd64
            env:
              GOOS: linux
              GOARCH: amd64
            runTests: true
          - name: linux 386
            env:
              GOOS: linux
              GOARCH: 386
            runTests: false
          - name: darwin amd64
            env:
              GOOS: darwin
              GOARCH: amd64
            runTests: false
          - name: darwin arm64
            env:
              GOOS: darwin
              GOARCH: arm64
            runTests: false
          - name: windows amd64
            env:
              GOOS: windows
              GOARCH: amd64
            runTests: false

    steps:
    - name: check out code into the Go module directory
      uses: actions/checkout@v4

    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
      id: go

    - name: get dependencies
      run: |
        export GOPATH=$HOME/go
        ./tools/install.sh
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: verify tooling
      run: |
        go version
        which golangci-lint
        golangci-lint version

    - name: build
      env: ${{ matrix.env }}
      run: go build -v ./cmd/... ./internal/...

    - name: test
      if: ${{ matrix.runTests }}
      run: go test -v ./... -count=1

    - name: lint
      if: ${{ matrix.runTests }}
      run: golangci-lint run ./...
